/**
 * SSC Class 9 curriculum topic whitelist.
 * Used by ExamConfigPanel for chapter dropdown selection.
 */
export const SSC_CLASS_9_TOPICS: Record<string, string[]> = {
  Math: [
    "Sets and Functions",
    "Real Numbers",
    "Algebraic Expressions",
    "Linear Equations in One Variable",
    "Linear Equations in Two Variables",
    "Simultaneous Linear Equations",
    "Quadratic Equations",
    "Ratio and Proportion",
    "Indices and Logarithms",
    "Geometry: Lines, Angles, Triangles",
    "Congruence of Triangles",
    "Similarity of Triangles",
    "Pythagoras Theorem",
    "Circles and Tangents",
    "Area and Perimeter",
    "Surface Area and Volume",
    "Statistics: Mean, Median, Mode",
    "Probability",
    "Trigonometric Ratios",
    "Trigonometric Identities",
    "Heights and Distances",
  ],
  Physics: [
    "Physical Quantities and Measurement",
    "Motion and Rest",
    "Speed, Velocity and Acceleration",
    "Newton's Laws of Motion",
    "Gravitation and Gravity",
    "Work, Energy and Power",
    "Pressure in Solids, Liquids and Gases",
    "Sound: Vibration, Frequency, Wave",
    "Light: Reflection, Refraction",
    "Heat and Temperature",
    "Expansion of Matter",
    "Electricity: Current, Voltage, Resistance",
    "Ohm's Law and Circuits",
    "Magnetic Effects of Electric Current",
    "Modern Physics and Radioactivity",
  ],
  Chemistry: [
    "Matter and Its Classification",
    "Atomic Structure",
    "Periodic Table",
    "Chemical Bonding",
    "Chemical Reactions and Equations",
    "Acids, Bases and Salts",
    "Mole Concept",
    "Solutions and Solubility",
    "Electrolysis",
    "Metals and Non-metals",
    "Hydrocarbons and Organic Chemistry Basics",
    "Environmental Chemistry",
    "Water: Properties and Treatment",
  ],
  Biology: [
    "Biology and Its Branches",
    "Cell Structure and Function",
    "Cell Division: Mitosis and Meiosis",
    "Classification of Living Organisms",
    "Kingdom Plantae",
    "Kingdom Animalia",
    "Nutrition in Plants and Animals",
    "Transport in Plants and Animals",
    "Gaseous Exchange and Respiration",
    "Excretory System",
    "Firmness and Locomotion",
    "Co-ordination: Nervous and Hormonal",
    "Reproduction in Plants and Animals",
    "Heredity and Evolution",
    "Biotechnology",
    "Ecology and Environment",
  ],
  "Higher Math": [
    "Sets and Relations",
    "Functions and Graphs",
    "Algebraic Formulas and Identities",
    "Polynomials",
    "Linear Inequalities",
    "Quadratic Equations and Graphs",
    "Arithmetic Progression",
    "Geometric Progression",
    "Coordinate Geometry: Distance, Section Formula",
    "Straight Lines",
    "Trigonometry: All Ratios and Identities",
    "Logarithms",
    "Permutations and Combinations",
    "Binomial Theorem",
    "Statistics: Variance and Standard Deviation",
    "Probability: Classical and Conditional",
  ],
};
