"""Add display_name and subjects_of_interest

Revision ID: 3917bfc03897
Revises: e173be882bf3
Create Date: 2026-05-26 19:08:58.110623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3917bfc03897'
down_revision: Union[str, Sequence[str], None] = 'e173be882bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learner_profiles', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('learner_profiles', sa.Column('subjects_of_interest', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learner_profiles', 'subjects_of_interest')
    op.drop_column('learner_profiles', 'display_name')
    # ### end Alembic commands ###
